syntax on
color evening
set guifont=Consolas:h11
set nu ts=4 sw=4 sts=4 et ai si cin hls ru t_Co=256
set mouse=a bs=2 ci nocp ar fencs=utf-8
set sm mat=0
filetype plugin indent on
inoremap {<CR>  {<CR>}<Esc>O
nnoremap <C-Up> <Up>ddp<Up>
nnoremap <C-Down> ddp